### ISSUE TITLE
Enhancing User Experience with a Progress Bar for Image Uploads

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/annotate-lab#10]
Uploading an image to a server can take time and depends on various factors. It would be nice to have a progress bar in the upload screen section.

Example progress bar can be found [here](https://v4.mui.com/components/progress/). 

![Screenshot 2024-06-06 at 1 56 01 PM](https://github.com/sumn2u/annotate-lab/assets/6531541/af3fc72a-8aaa-463d-9970-3daf2392dc45)

**Comment by OmG2011** [comment]
I'd like to work on this issue.

**Comment by sumn2u** [comment]
Closing this issue as it's fixed in #11 .
