### ISSUE TITLE
[feature request] allow a large numer of files

### ISSUE THREAD

**Issue by leo-smi** [sumn2u/annotate-lab#124]
**Is your feature request related to a problem? Please describe.**
when uploading too many files an error pops out

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/e8067897-cd46-4522-b02e-1dd2925f4894)

**Describe the solution you'd like**
Add all my images dataset at once (or see the suggestion)

**Describe alternatives you've considered**
None

**Suggestion**
Add a project folder instead upload the files

**Comment by sumn2u** [comment]
Thank you for the feature request. To increase the file size limit, you can replace the UPLOAD_LIMIT value found [here](https://github.com/sumn2u/annotate-lab/blob/master/client/src/config.js#L13). 

```js
const config = {
    DOCS_URL:"https://annotate-docs.dwaste.live/",
    SERVER_URL,
    UPLOAD_LIMIT: 5, // replace this to allow large numbers
    OUTLINE_THICKNESS_CONFIG : {
      POLYGON: 2,
      CIRCLE: 2,
      BOUNDING_BOX: 2
    }
  };
```

**Comment by sumn2u** [comment]
@leo-smi  I've increased the file upload limits to `500`. If you need a higher limit, you can manually adjust it by setting the desired value for UPLOAD_LIMIT in the config.js file

**Comment by leo-smi** [comment]
> @leo-smi I've increased the file upload limits to `500`. If you need a higher limit, you can manually adjust it by setting the desired value for UPLOAD_LIMIT in the config.js file

thank you
