### ISSUE TITLE
[feature request] Save current project checkpoint for large datasets

### ISSUE THREAD

**Issue by leo-smi** [sumn2u/annotate-lab#128]
**Is your feature request related to a problem? Please describe.**

- Save current project checkpoint for large datasets in case need to interrupt the server and client
<br>

**Describe the solution you'd like**

- Create a project/task state for the uploaded images and labeling status to avoid lost the checkpoint
- Keep the images in the original folder (instead upload), but neet to alert the user to make a backup before editing this folder
- Save the downloads to the project folder.
<br>

**Describe alternatives you've considered**

There's no alternatives for now.
<br>

**Comment by sumn2u** [comment]
Thanks for the feature request. Currently, we save the state of the annotated image based on the annotation types in `csv` formats. This state is then used with the uploaded image to download the masked or annotated image.

If there's any interruption on the server or client side, we can restart the servers, and they will resume from the last saved state. However, one limitation is that it won't display the last annotated image; instead, it will start from the beginning. I can work on fixing this issue.
