### ISSUE TITLE
[feature request] Add a .bat file to run the client, server and the localhost. Or add to the documentation suggestion.

### ISSUE THREAD

**Issue by leo-smi** [sumn2u/annotate-lab#137]
**Is your feature request related to a problem? Please describe.**

- add a .bat file to run the client, server and the localhost

**Describe the solution you'd like**

- Run client and server with a click

```
cd client
start cmd /k "npm install & start http://localhost:5174/ & npm start"
cd ../server
start cmd /k "flask run"
pause

```

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/f66c53b6-8a50-4ce3-ae8a-35e6070a9a6a)

PS: I can't try a batch file for linux for now...

**Comment by sumn2u** [comment]
@leo-smi  I can take care of linux. Can you create a `.bat` for the windows?

**Comment by leo-smi** [comment]
> @leo-smi I can take care of linux. Can you create a `.bat` for the windows?

sure

**Comment by sumn2u** [comment]
> > @leo-smi I can take care of linux. Can you create a `.bat` for the windows?
> 
> sure

Thanks. BTW, don't we have to include the python package installation here?

```sh
cd client
start cmd /k "npm install & start http://localhost:5174/ & npm start"
cd ../server
start cmd /k "flask run"
pause
```

**Comment by leo-smi** [comment]
> > > @leo-smi I can take care of linux. Can you create a `.bat` for the windows?
> > 
> > 
> > sure
> 
> Thanks. BTW, don't we have to include the python package installation here?
> 
> ```shell
> cd client
> start cmd /k "npm install & start http://localhost:5174/ & npm start"
> cd ../server
> start cmd /k "flask run"
> pause
> ```

yes, I will do some tests for requiremtns.txt.

**Comment by leo-smi** [comment]
lmao I'm a newbie to git

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/7d546267-c008-4180-87ed-8b35dccd0203)

BTW here is the code for bat file:

filename: RUN_ON_WINDOWS.bat

```
cd client
start cmd /k "npm install & start http://localhost:5174/ & npm start"
cd ../server
start cmd /k "pip install -r requirements.txt & flask run"
pause

```

**Comment by sumn2u** [comment]
Thanks for the code. I will create it.

**Comment by sumn2u** [comment]
@leo-smi  Can you check this code? If it works in windows?

```sh
cd client

start cmd /k "npm install && start http://localhost:5174/ && npm start"

cd ../server

IF NOT EXIST venv (
    python -m venv venv
)

start cmd /k "call venv\Scripts\activate && pip install -r requirements.txt && flask run"

pause
```

**Comment by leo-smi** [comment]
> ```shell
> cd client
> 
> start cmd /k "npm install && start http://localhost:5174/ && npm start"
> 
> cd ../server
> 
> IF NOT EXIST venv (
>     python -m venv venv
> )
> 
> start cmd /k "call venv\Scripts\activate && pip install -r requirements.txt && flask run"
> 
> pause
> ```

sure, I will try it.

**Comment by leo-smi** [comment]
the env worked fine

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/54049237-46fa-4256-847e-769bb446827d)

**Comment by sumn2u** [comment]
> > @leo-smi Can you check If this code works in windows?
> > ```shell
> > cd client
> > 
> > start cmd /k "npm install && start http://localhost:5174/ && npm start"
> > 
> > cd ../server
> > 
> > IF NOT EXIST venv (
> >     python -m venv venv
> > )
> > 
> > start cmd /k "call venv\Scripts\activate && pip install -r requirements.txt && flask run"
> > 
> > pause
> > ```
> 
> kind worked but I have no idea why the script changed the port to 5173
> 
> ![image](https://private-user-images.githubusercontent.com/20663547/347173848-c1b98d8b-e961-471b-9535-386ab237c2f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjcxNDksIm5iZiI6MTcyMDU2Njg0OSwicGF0aCI6Ii8yMDY2MzU0Ny8zNDcxNzM4NDgtYzFiOThkOGItZTk2MS00NzFiLTk1MzUtMzg2YWIyMzdjMmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NWVhZmE2ODNkOTBjNDM1ZmVlMTU0YWRmMTZmNDNlOTI4OTE1OWNhMzNkNDE4ZDE5YTMzYjEzMjVlYmM2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_Veexl5QtOCyy89vMlf3J185hh-wNwkVF1ws8zv6yI)

 @leo-smi  The `npm start` starts the application using port `5173 ` which is defined [here](https://github.com/sumn2u/annotate-lab/blob/master/client/vite.config.js#L28). Think we can remove the `start http://localhost:5174/`. 

Can you check one more time with below code? 

```sh
cd client

start cmd /k "npm install && npm start"

cd ../server

IF NOT EXIST venv (
    python -m venv venv
)

start cmd /k "call venv\Scripts\activate && pip install -r requirements.txt && flask run"

pause
```

**Comment by leo-smi** [comment]
> @leo-smi The `npm start` command starts the application using port `5173 ` which is defined [here](https://github.com/sumn2u/annotate-lab/blob/master/client/vite.config.js#L28). Think we can remove the `start http://localhost:5174/`.


Can we keep like below? the code is to open the browser page. Once the port will not change I think is a gain time.

```
cd client

start cmd /k "npm install && start http://localhost:5173/ && npm start"

cd ../server

IF NOT EXIST venv (
    python -m venv venv
)

start cmd /k "call venv\Scripts\activate && pip install -r requirements.txt && flask run"

pause
```

**Comment by leo-smi** [comment]
The server page keeps loading and don't open. Now the server is running at http://localhost:5174/ . So you can remove the line ```start http://localhost:5173/``` for now. For some reason the port keep changing. 

```
cd client

start cmd /k "npm install && npm start"

cd ../server

IF NOT EXIST venv (
    python -m venv venv
)

start cmd /k "call venv\Scripts\activate && pip install -r requirements.txt && flask run"

pause
```

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/87840cce-4d25-4032-bc80-4a61041f0a6b)

**Comment by leo-smi** [comment]
Is there a way to kill the client when closing the prompt? I have to clients running at http://localhost:5175/ and http://localhost:5174/ and I think there's a third running at http://localhost:5173/

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/4602c89a-5964-432b-9582-24e24a12faca)

**Comment by leo-smi** [comment]
> This code should do the job.
> 
> ```shell
> cd client
> npm install
> 
> start "Client" cmd /c "npm start"
> 
> cd ../server
> 
> IF NOT EXIST venv (
>     python -m venv venv
> )
> 
> 
> call venv\Scripts\activate
> pip install -r requirements.txt
> 
> start "Server" cmd /c "flask run"
> 
> pause
> 
> taskkill /FI "WINDOWTITLE eq Client"
> taskkill /FI "WINDOWTITLE eq Server"
> ```

Did not work. The prompts windows just closed all.

**Comment by leo-smi** [comment]
I tried a lot of codes and nothing is working properly. Once the node task is killed, opening a new client do not load the webpage. Even finding the specific PID of the client port. 

I suggest removing the batch files for now and open to the future as a project. 

If you want to keep the linux batch is up to you. 

Thanks!

**Comment by sumn2u** [comment]
Thanks for trying. I'm removing both the script for now as it doesn't make sense to have support for one but not for other.
