### ISSUE TITLE
[feature request] Add YOLO annotation normalization diagram and code to the docs/readme

### ISSUE THREAD

**Issue by leo-smi** [sumn2u/annotate-lab#148]
I did a diagram to help people understand the normalization properly, once I had the same difficulty on it. I fisrtly posted to the ultralytics page [here](https://github.com/ultralytics/yolov5/issues/7135).

```
# Example conversion from non-normalized (xmax, ymax, xmin, ymin) to normalized (x_center, y_center, width, height)

WIDTH = 640  # annotated image width
HEIGHT = 640  # annotated image height

# Assuming row contains your bounding box coordinates
width = row['xmax'] - row['xmin']
height = row['ymax'] - row['ymin']
x_center = row['xmin'] + (width / 2)
y_center = row['ymin'] + (height / 2)

# Normalize the coordinates
content = f"{class_id} {x_center / WIDTH} {y_center / HEIGHT} {width / WIDTH} {height / HEIGHT}"
```

Diagram in SVG format:

![Normalize-Annotations](https://github.com/user-attachments/assets/ac9b3693-f985-4f39-83e4-15457bec6e69)

**Comment by sumn2u** [comment]
It's informative. Thanks for the content. 🥇

**Comment by leo-smi** [comment]
> It's informative. Thanks for the content. 🥇

Happy to help.
