### ISSUE TITLE
Translations fail to apply when the locale is not set to en-US or de-DE.

### ISSUE THREAD

**Issue by linyers** [sumn2u/annotate-lab#17]
Translation isn't provided when my localization isn't set to en-US or de-DE, leaving the translation key name as is.

Steps to Reproduce:
- Change the browser language to any language other than English or German (Deutsch).
- Restart the browser.
- Navigate through the [application](https://annotate.dwaste.live/)

![2024-06-09-011123_557x638_scrot](https://github.com/sumn2u/annotate-lab/assets/134330318/f7a5c0e9-c1b3-482c-92b0-072fcd4301d2)

**Comment by sumn2u** [comment]
@linyers Thanks for creating this issue 🙏
