### ISSUE TITLE
Enhancing Image Masking: Configurable Default Color Selection

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/annotate-lab#20]
Currently, when masking the image, a default [black](https://github.com/sumn2u/annotate-lab/blob/master/server/app.py#L344) color is selected. 

![image](https://github.com/sumn2u/annotate-lab/assets/6531541/65685c7b-e5a0-47f0-91c6-7020a70aea18)

Update the logic to allow this value to be loaded from a configuration file.

**Comment by Mews** [comment]
@sumn2u 
Since it wasn't supper clear, is there an existing configuration file where this value should be loaded from, or is creating a configuration file also required? And if so, where should It be located

**Comment by sumn2u** [comment]
> @sumn2u Since it wasn't supper clear, is there an existing configuration file where this value should be loaded from, or is creating a configuration file also required? And if so, where should It be located, and do you have any preferences for the file format


@Mews  We currently don't have the configuration file. This task will involve creating a configuration file called `config.py` where we will define `MASK_BACKGROUND_COLOR` and set its value. The file will be added to the `server` folder and used in `app.py`.

An example of configuration file along its usage is shown [here](https://exploreflask.com/en/latest/configuration.html).
