### ISSUE TITLE
Move docs URL's to configuration file 

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/annotate-lab#24]
In this project, we have two external links that points to "https://annotate-docs.dwaste.live/". You can find them in 
the [SetupPage](https://github.com/sumn2u/annotate-lab/blob/master/client/src/SetupPage/index.jsx#L113) and [DemoSite](https://github.com/sumn2u/annotate-lab/blob/master/client/src/DemoSite/index.jsx#L163) files. 

Create a configuration file inside the client folder that is responsible for setting the Docs URL.

**Comment by harith-hacky03** [comment]
I am ready to work on it. Can you assign me?

**Comment by harith-hacky03** [comment]
@sumn2u  Can i add it in .env file and link it back?

**Comment by sumn2u** [comment]
> @sumn2u Can i add it in .env file and link it back?

Yes, you can. Ideally, it would be nice to have a separate configuration file.

**Comment by harith-hacky03** [comment]
@sumn2u  Yeah it's done I hope you reviewed it . Can you merge it now?

**Comment by sumn2u** [comment]
> @sumn2u Yeah it's done I hope you reviewed it . Can you merge it now?

Sure.
