### ISSUE TITLE
Crypt module not supported on windows

### ISSUE THREAD

**Issue by harith-hacky03** [sumn2u/annotate-lab#25]
![image](https://github.com/sumn2u/annotate-lab/assets/108193091/d103dda2-9eda-4dc3-b9b6-f6700da791a2)

Steps to obtain:
Follow the steps on the readme file

**Comment by harith-hacky03** [comment]
Can I start working on it ?

**Comment by sumn2u** [comment]
> Can I start working on it ?

Sure.

**Comment by sumn2u** [comment]
@harith-hacky03  I removed the `crypt` module as it was unnecessary. It should work properly on Windows now.

**Comment by sumn2u** [comment]
Tested in Windows 10. The server is running without a problem.

![e798c4f5-9ce0-4026-b699-2d0077b720f7](https://github.com/sumn2u/annotate-lab/assets/6531541/e7820f0f-b5d9-48d1-9593-8abaa5cbdf62)
