### ISSUE TITLE
Show/Hide Download, Clone, and Save buttons

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/annotate-lab#3]
The "Download," "Clone," and "Save" buttons should only be displayed when there are regions present.

<img width="289" alt="button-controls" src="https://github.com/sumn2u/annotate-lab/assets/6531541/18dfbfe5-90d1-4176-ba6b-c4fd0c637239">

**Comment by linyers** [comment]
I can do it, please assign this issue to me.
