### ISSUE TITLE
Configurable Outline Thickness for Drawing Shapes

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/annotate-lab#42]
During masking, we have set the outline thickness using `width` to only one region and it's hard coded. 

```js
draw.ellipse([rx, ry, rx + rw, ry + rh], outline=color, width=3, fill=color)
```
![image](https://github.com/sumn2u/annotate-lab/assets/6531541/6bcc0400-0b61-44c3-83c5-93b4ddbc1d5a)

Introduce a configuration parameter (`OUTLINE_THICKNESS`) to control the thickness of outlines for shapes drawn using `draw.polygon` and `draw.rectangle`, and also update the `draw.ellipse` width value with this.

### Benefits
- Enhances consistency and flexibility in outline appearance.
- Simplifies maintenance by managing outline thickness globally.

### Implementation Plan
1. Add `OUTLINE_THICKNESS` parameter to [configuration settings](https://github.com/sumn2u/annotate-lab/blob/master/server/config.py).
2. Modify drawing functions to use this parameter.
3. Update documentation and examples accordingly in `README.md`.

### Acceptance Criteria
- Drawing functions correctly utilize `OUTLINE_THICKNESS`.
- Global adjustment of outline thickness validated.
- Changes integrated without regression.

**Comment by DQ4443** [comment]
Hello sumn2u, I would like to help with this issue.

**Comment by DQ4443** [comment]
Hey Sumn2u, I review the flask section of the code and updated the draw.foo() functions with a config variable, but as the only draw.foo functions are in the download routes, the width change is only reflected in the downloaded images and not in the preview. Is this what you were looking for, or should I update the frontend/js parts of the code base too?

preview screen:
![image](https://github.com/sumn2u/annotate-lab/assets/93507257/281cc096-b5f2-4660-940d-46f63aa6c8b4)

downloaded:
![image](https://github.com/sumn2u/annotate-lab/assets/93507257/222b35cb-e06e-4486-8e18-5fc2e4d80c41)

Also with regards to the README file, there is currently no mention of modifying the config.py file for the MASK_BACKGROUND_COLOR variable either, so should I add a new section to detail how a user can optionally customize these variables? 

I've also noticed several other config variables that were defined in the main app.py file instead of in the config.py file. Would you like to migrate these variables all to the config file?

Lastly, I noticed that the current flask code uses the deprecated (and now redundant) flask jsonify method. Would you like to update the code to remove the "jsonify()"s ?

**Comment by sumn2u** [comment]
@DQ4443  Thanks for providing the detailed information. I was not aware of the thickness issue with large numbers. Ideally, it would be nice to have a slider in the UI to control the thickness. Based on its value, the Flask application will adjust accordingly and reflect the changes in the downloaded file.

For now, we can use the config variable value and apply it in the Flask application. As for the UI, we can create a separate task to add a slider, limiting the upper bound to 5 to mitigate the thickness issue. This slider will then be linked to the Flask application.

> Also with regards to the README file, there is currently no mention of modifying the config.py file for the MASK_BACKGROUND_COLOR variable either, so should I add a new section to detail how a user can optionally customize these variables?

 I have added the customization instructions in the documentation section [documentation section](https://annotate-docs.dwaste.live/overview/customization) and will include more information once it's completed.

> I've also noticed several other config variables that were defined in the main app.py file instead of in the config.py file. Would you like to migrate these variables all to the config file?

It would be great if you could move them to the config file. I suggest creating an issue for this task and then assigning it to yourself if you are working on it.

> Lastly, I noticed that the current flask code uses the deprecated (and now redundant) flask jsonify method. Would you like to update the code to remove the "jsonify()"s ?

Sure. 

Thanks for providing the feedback. I suggest creating separate issues and assigning yourself to the ones you want to work on.

**Comment by sumn2u** [comment]
The current outline width used in the UI is defined in [RegionShapes](https://github.com/sumn2u/annotate-lab/blob/master/client/src/RegionShapes/index.jsx). Here, you can see that based on the tools, we have various `strokeWidth` values. We might need to create a map based on the selected tools and use it in the server.

**Comment by DQ4443** [comment]
> @DQ4443 Thanks for providing the detailed information. I was not aware of the thickness issue with large numbers. Ideally, it would be nice to have a slider in the UI to control the thickness. Based on its value, the Flask application will adjust accordingly and reflect the changes in the downloaded file.
> For now, we can use the config variable value and apply it in the Flask application. As for the UI, we can create a separate task to add a slider, limiting the upper bound to 5 to mitigate the thickness issue. This slider will then be linked to the Flask application.

Cool I'll just implement the config variable in the backend first and create a separate PR for the frontend.

> 
> > Also with regards to the README file, there is currently no mention of modifying the config.py file for the MASK_BACKGROUND_COLOR variable either, so should I add a new section to detail how a user can optionally customize these variables?
> 
> I have added the customization instructions in the documentation section [documentation section](https://annotate-docs.dwaste.live/overview/customization) and will include more information once it's completed.

Would you like me to add a section in README file to direct users to the documentation?

> 
> > I've also noticed several other config variables that were defined in the main app.py file instead of in the config.py file. Would you like to migrate these variables all to the config file?
> 
> It would be great if you could move them to the config file. I suggest creating an issue for this task and then assigning it to yourself if you are working on it.
> 
> > Lastly, I noticed that the current flask code uses the deprecated (and now redundant) flask jsonify method. Would you like to update the code to remove the "jsonify()"s ?
> 
> Sure.

I'll create separate PRs for these two issues

**Comment by sumn2u** [comment]
> Would you like me to add a section in README file to direct users to the documentation?

That would be great.
