### ISSUE TITLE
Migrate config variables to config.py file

### ISSUE THREAD

**Issue by DQ4443** [sumn2u/annotate-lab#52]
Currently there are several config variables defined in the main app.py file. These variables should be migrated to the config.py file for easier access.

**Comment by sumn2u** [comment]
@DQ4443 Thanks for creating this task. Is it possible to provide more information to it?

**Comment by DQ4443** [comment]
I was initially referring to the UPLOAD_FOLDER and CORS_HEADERS config variables, but upon reviewing the codebase more closely, I see that it doesn't make sense to move the declaration of those two config variables to the config.py file.
