### ISSUE TITLE
Adjust Annotation Page Height to Cover Full Screen

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/annotate-lab#6]
The height of the current annotation page is set to `80vh`  which can be found [here](https://github.com/sumn2u/annotate-lab/blob/master/client/index.html#L27). Increase the height to cover the full screen.

![full-screen](https://github.com/sumn2u/annotate-lab/assets/6531541/56741eb3-6ad2-4b93-bf69-5f7f49b6d9fd)

**Comment by OmG2011** [comment]
I'd like to work on this issue.
