### ISSUE TITLE
Issue uploading .webp files: Incorrect error message displayed

### ISSUE THREAD

**Issue by OmG2011** [sumn2u/annotate-lab#8]
While trying to upload an image to the client, I encountered an issue specifically with .webp files. The error message "Couldn't connect server" is displayed, which is misleading as the server connection is not the problem. This issue does not occur when uploading .jpeg files.

Steps to Reproduce:

1. Navigate to the image upload feature in the application.
2. Attempt to upload a .webp file.
3. Observe the error message displayed.

Expected Behavior:
A specific error message should be displayed indicating the actual issue with the .webp file upload.

Actual Behavior:
The error message "Couldn't connect server" is displayed.

**Comment by VinayakGaikwad101** [comment]
I'm interested to work on this issue

**Comment by sumn2u** [comment]
@VinayakGaikwad101  I think you can do something like this to fix the issue.

```catch (error) {
      const errorResponse = error?.response?.data
      if (errorResponse) {
        showSnackbar(errorResponse?.message, 'error');
      }else {
        showSnackbar(t("error.server_connection"), 'error')
      }
      console.error('Error uploading images:', error);
    }```
