### ISSUE TITLE
[enhancement] Open the floating label mark box in the right side of the image instead bottom

### ISSUE THREAD

**Issue by leo-smi** [sumn2u/annotate-lab#89]
BEHAVIOR:
![image](https://github.com/sumn2u/annotate-lab/assets/20663547/8feb57d6-8b6f-4728-b290-8a9da7c6f81b)

EXPECTED:
An option to open the box in the right side of the image to be more visible.

**Comment by sumn2u** [comment]
@leo-smi Is it possible to attach the image too?

**Comment by leo-smi** [comment]
> @leo-smi Is it possible to attach the image too?

Sorry, which image? The tomato or the screenshot of the expected behavior?

**Comment by leo-smi** [comment]
Sure:

![IMG_20230819_162635_HDR](https://github.com/sumn2u/annotate-lab/assets/20663547/691693b9-182a-412c-aa76-924dcd466323)
![IMG_20230819_162644_HDR](https://github.com/sumn2u/annotate-lab/assets/20663547/5eb6ba65-938c-4013-a64d-1627a74aa48a)
![IMG_20230819_162654_HDR](https://github.com/sumn2u/annotate-lab/assets/20663547/0890461f-f3f2-471f-9008-44161428f18a)

**Comment by sumn2u** [comment]
@leo-smi  the fixes are merged into the master branch.

**Comment by leo-smi** [comment]
Thank you, it's working. 

![image](https://github.com/sumn2u/annotate-lab/assets/20663547/3d78fdca-3c96-46b0-acc6-b271ba2ca16c)
